### ISSUE TITLE
Telegram link

### ISSUE THREAD

**Issue by turian** [tshu-w/tshu-w#1]
Hi Tianshu!

Great meeting you on this thread: https://github.com/ashleve/lightning-hydra-template/issues/443

I'd love to chat more about your work and mine but your telegram link is broken. Do you have another telegram? (Or message me at @mygithubusername on telegram.)

**Comment by tshu-w** [comment]
Hi @turian! Nice to meet you. I clear my username to alleviate spam. I have sent you a message on telegram. Let me know if you didn't receive it.
